apiVersion: apps/v1
kind: Deployment
metadata:
  name: twoge-db
  namespace: flo-twoge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twoge-db
  template:
    metadata:
      labels:
        app: twoge-db
    spec:
      initContainers:
        - name: init-volume
          image: busybox
          command: ["sh", "-c", "mkdir -p /pgdata/pgroot"]
          volumeMounts:
            - name: postgres-storage
              mountPath: /pgdata
      containers:
        - name: postgres
          image: postgres:13
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: twoge-config
                  key: DATABASE_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: twoge-secrets
                  key: DATABASE_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: twoge-secrets
                  key: DATABASE_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgroot
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
