name: Create Flo EKS Cluster

on:
  workflow_dispatch:

jobs:
  create-flo-cluster:
    name: Provision EKS Cluster for Flo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install eksctl
        run: |
          curl --silent --location "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin

      - name: Create EKS cluster for Flo 🚀
        run: |
          eksctl create cluster \
            --name ${{ secrets.EKS_CLUSTER_NAME }} \
            --region ${{ secrets.AWS_REGION }} \
            --nodes 2 \
            --node-type t3.small \
            --node-volume-size 30 \
            --version 1.29 \
            --with-oidc \
            --tags "project=twoge,env=dev,owner=flo" \
            --managed

      - name: Install Amazon EBS CSI Driver Addon
        run: |
          aws eks create-addon \
            --cluster-name ${{ secrets.EKS_CLUSTER_NAME }} \
            --region ${{ secrets.AWS_REGION }} \
            --addon-name aws-ebs-csi-driver \
            --addon-version v1.30.0-eksbuild.1 \
            --resolve-conflicts OVERWRITE \
            || echo "Addon might already exist — continuing"

      - name: Attach AmazonEBSCSIDriverPolicy to Node Group Role
        run: |
          STACK_NAME=$(aws cloudformation list-stacks \
            --stack-status-filter CREATE_COMPLETE UPDATE_COMPLETE \
            --query "StackSummaries[?starts_with(StackName, 'eksctl-${{ secrets.EKS_CLUSTER_NAME }}-nodegroup')].StackName" \
            --output text)

          echo "Detected NodeGroup Stack: $STACK_NAME"

          ROLE_NAME=$(aws cloudformation describe-stacks \
            --stack-name "$STACK_NAME" \
            --query "Stacks[0].Outputs[?OutputKey=='NodeInstanceRole'].OutputValue" \
            --output text | awk -F'/' '{print $2}')

          echo "Attaching AmazonEBSCSIDriverPolicy to role: $ROLE_NAME"

          aws iam attach-role-policy \
            --role-name "$ROLE_NAME" \
            --policy-arn arn:aws:iam::aws:policy/AmazonEBSCSIDriverPolicy
