name: Create Flo EKS Cluster

on:
  workflow_dispatch:

jobs:
  create-flo-cluster:
    name: Provision EKS Cluster for Flo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install eksctl, jq
        run: |
          curl --silent --location "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin
          sudo apt-get update && sudo apt-get install -y jq unzip curl

      - name: Create EKS cluster for Flo
        run: |
          eksctl create cluster \
            --name ${{ secrets.EKS_CLUSTER_NAME }} \
            --region ${{ secrets.AWS_REGION }} \
            --nodes 2 \
            --node-type t3.small \
            --node-volume-size 30 \
            --version 1.29 \
            --with-oidc \
            --tags "project=twoge,env=dev,owner=flo" \
            --managed \
            --wait

      - name: Create IAM service account for EBS CSI driver
        run: |
          eksctl create iamserviceaccount \
            --region ${{ secrets.AWS_REGION }} \
            --name ebs-csi-controller-sa \
            --namespace kube-system \
            --cluster ${{ secrets.EKS_CLUSTER_NAME }} \
            --attach-policy-arn arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy \
            --approve \
            --role-only \
            --role-name AmazonEKS_EBS_CSI_DriverRole_flo

      - name: Install Amazon EBS CSI Driver Addon
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          aws eks create-addon \
            --cluster-name ${{ secrets.EKS_CLUSTER_NAME }} \
            --region ${{ secrets.AWS_REGION }} \
            --addon-name aws-ebs-csi-driver \
            --addon-version v1.30.0-eksbuild.1 \
            --service-account-role-arn arn:aws:iam::$ACCOUNT_ID:role/AmazonEKS_EBS_CSI_DriverRole_flo \
            --resolve-conflicts OVERWRITE \
            || echo "Addon might already exist — continuing"
